### ISSUE TITLE
Develop a concept of 'check staleness'

### ISSUE THREAD

**Issue by hashbrowncipher** [Yelp/sensu#2] opened 2015-01-20 22:28 UTC
Right now, there is no way for a standalone check to become CRITICAL if no event is received for more than a defined period of time.  Creating such functionality would allow us to replace Nagios passive checks with masqueraded Sensu checks, and simplify the solution to #1.

**Comment by hashbrowncipher** [comment] 2015-01-20 22:40
Mailing list [thread](https://groups.google.com/d/msg/sensu-dev/_yIoukBgAf0/ePsqRRVUbhQJ)

**Comment by mks-m** [comment] 2015-01-21 12:15
here's an idea - create a sensu extension handler that will:

1) update per-check timestamps in redis
2) have eventmachine periodic timer to check if anything timed out and generate a new "critical" event for every

that way we don't have to deviate further from sensu mainline and it will be easy to opt-in-out of the extension for checks/clients where we don't want to have such functionality (just skip the staleness handler in the config)

**Comment by mikery** [comment] 2015-01-21 13:22
Great feature, I'd love to see this feature implemented upstream too. My use case is for monitoring backup scripts, and having Sensu raise an alert if a "backup success" check is not submitted every x hours.

**Comment by hashbrowncipher** [comment] 2015-01-21 17:32
@mikery:

If your backups run on the same node every time, you can use the workaround of touch(1)ing a file whenever they succeed, and then monitoring the age of that file.  I've adapted our very short wrapper and put it up as a [gist](https://gist.github.com/hashbrowncipher/7f7e6075a64bdb037b67) if it helps your use case.  We have Puppet place these files initially (so that the check passes from the start), and then we use check_file_age within a Sensu standalone check to check the freshness of the file.  We run this check at intervals of min(staleness_threshold / 5, 1 hour).  I'll start the ball rolling on open sourcing our puppet cron module, which contains all of this logic.

Of course, this only works if your jobs run on the same host all of the time.  Otherwise, you want the functionality described in this issue.

**Comment by hashbrowncipher** [comment] 2015-01-21 17:36
@keymone:

Sounds like a nice idea.  I don't know much about extension handlers, so I'll have to read up.  Sensu already stores check execution time in redis (I think the key is "execution:client_name:check_name")

**Comment by mks-m** [comment] 2015-01-21 17:59
@hashbrowncipher right, i forgot about that. things are even simpler then - a sensu extension that nothing will subscribe to will be running a periodic timer with a block to loop over checks to collect those with non-nil keepalive key which gets compared to latest execute time and alert is triggered if $conditions.

something like this: https://gist.github.com/keymone/04c4670a466b2af85236

**Comment by portertech** [comment] 2015-01-21 18:42
We could create a mechanism in core, similar to client keepalives. When processing a check result, we could store a key/value in redis, using client:check as the key, interval:timestamp as the value. We could then have a Sensu server master EM timer to iterate through the pairs, looking for stale checks.

**Comment by solarkennedy** [comment] 2015-01-21 18:48
Yea, I agree that a mechanism simliar to client keepalives is probably the best way to go about this.
@keymone I think has the right idea. For reference we would be emulating this code (`determine_stale_clients`)
https://github.com/sensu/sensu/blob/cec0044ca96221709d4bbecf45c6f5f1133214b2/lib/sensu/server.rb#L562-605

I think we should have a `determine_stale_checks` :)

But, with a client we can delete it when we are done. How would we delete this stale check?

**Comment by portertech** [comment] 2015-01-21 18:53
@solarkennedy Need to create a reference to a client and have the gc done when the client is deleted.

**Comment by mks-m** [comment] 2015-01-21 20:02
@portertech @solarkennedy 

the idea behind extension is to not require sensu upgrade, it can easily be integrated into sensu core later

the #run of extension could maintain the list of currently keepalived checks in redis for performance reasons but this would also allow deleting stale checks on demand

**Comment by mikery** [comment] 2015-01-22 07:56
@hashbrowncipher Thanks for the workaround. Most of my backup jobs do indeed run from a single host, so the file age method will be great for that.

**Comment by roobert** [comment] 2015-01-23 16:52
I've been looking at adding check staleness and was wondering why only check data for failing events is stored in redis under `events:<host>`. It would be nice to be able to see `check[:output]` for healthy checks because quite often interesting information is output by the check scripts.

If the check data was stored for normal checks then we can use the `check[:interval]` and `check[:executed]` values to work out which checks are stale and also the check data could be used as a template when adding an event onto the event queue to warn of check staleness.

@portertech - I'm assuming there's a reason why check data for checks with status 0 aren't already stored in redis but I'm not sure what it is, could you shed some light on this and also any insight you have on this implementation would be appreciated!

edit: I'm assuming the reason status 0 check event data isn't transmitted by clients is because it would vastly increase the amount of traffic and storage necessary..

edit: could we store check data for checks with `check[:metric]` set to `metric`? These types of checks always send event data to the sensu-server so it would only mean an increase in stored data in redis rather than additional traffic too. It would restrict check keepalives to this type, though.

The alternative is to forget having the extra event data for checks with status 0 stored in redis and revert to the original plan of storing the check interval metadata somewhere.

Also, I'm not sure that we need to record a timestamp for each check as that seems to already be being recorded to `executed:<host>:<check>`?

**Comment by portertech** [comment] 2015-01-26 19:28
@roobert all check results are "transmitted" by client, as that's how events are resolved etc. Sensu does not store OK results to reduce the amount of data stored, for Sensu's concern has always been in what's broken, while allowing users to send that OK data elsewhere (that can effectively present it). Green light dashboards do not scale and most of the time the information users want is best stored in a time series database, eg. measurments. I'm curious if we can change how the last execution timestamp is stored, tack on the run interval, so that we can detect stale checks w/o making fundamental changes. Thoughts?

**Comment by roobert** [comment] 2015-02-02 22:21
Bit of progress: https://github.com/roobert/sensu/compare/a6db42dce674044b7b1ff8e0ea0304d95ec9054f%5E%5E...a6db42dce674044b7b1ff8e0ea0304d95ec9054
- changed `execution:<hostname>:<check_name>` to be a hash with `interval` and `last_execution` keys.
- implemented a determine_stale_checks method

Need to test these changes tomorrow, will report back on how I get on..

**Comment by ohaddal** [comment] 2015-02-03 16:32
@portertech 

Just out of curiosity, how much of a performance hit would it be to allow status 0 event data? 

Personally I'd be happy with current state (no history) and being able to trigger this on specific checks only, i.e <code>"stateful": true </code>. I'm running into more and more cases where time series just doesn't cut it, or ends up being an extremely clunky way to present the data.

**Comment by roobert** [comment] 2015-02-04 09:08
@ohaddal I've been thinking about this too and based off what @portertech said I think the best way to add this type of functionality would be to create a handler that writes OK event data to redis. Coupled with a Uchiwa plugin (or something) I think this would be a good way of providing the green-light type dashboards that we're used to with Nagios.

I'd be interested in hearing whether @palourde has any plans for Uchiwa to support plugins, or whether he would be open to the idea of adding some kind of green-light functionality to Uchiwa to work with OK data stored in redis.

**Comment by solarkennedy** [comment] 2015-02-04 16:23
Status 0 event data _does_ go to the server, that is fine.
https://github.com/sensu/sensu/blob/master/lib/sensu/client.rb#L101-105

Handlers do act on event 0 data, but you only get the one resolve event.
https://github.com/sensu/sensu/blob/master/lib/sensu/server.rb#L422-L441 ?

For the purpose of this ticket, we need (I think) what @roobert has built so far: storing the timestamp and interval + determine_stale_checks. That should be enough to have an extension or sensu-core (determine_stale_checks) to be able to alert on checks that have not reported in.

Green light dashboards could be possible after this change, but are outside of the scope for now. In order to build a green light dashboard uchiwa and the sensu apis would have to be modified to present this data, but one step at a time.

But for determine_stale_checks, I _do_ want to be able to configure the threshold:
https://github.com/roobert/sensu/compare/a6db42dce674044b7b1ff8e0ea0304d95ec9054f%5E%5E...a6db42dce674044b7b1ff8e0ea0304d95ec9054#diff-b1352d95ed2d2b3454a9cbf22e47a38aR575

For my use case, simply waiting for after the interval is not enough, also a boolean ("stateful":true) is not enough. I want a time interval, so I can just say "alert if not heard from in 24 hours". (I don't actually want human readable units, seconds is fine at this level)

Because not _every_ check needs to spawn a new alert just because it disappears. And different use cases need different ttls.

I vote we make determine_stale_checks only do anything if this data is present. I like `watchdog_timer` from the electronics world. That is how I think of this. consul calls this `ttl`. Other places at yelp we call this `check_staleness`, and nagios calls it `check_freshness`.

**Comment by roobert** [comment] 2015-02-04 21:03
@solarkennedy, @portertech: What about leaving the default as-is (which is the same behaviour as Nagios) having watchdog_timer override the default, and have special value '0' disable keepalives for the check?

The reason I think this would be good is because by default I don't have to do anything, I just want to set watchdog_timer to 0 or a certain value in special cases.. what do you think?

**Comment by solarkennedy** [comment] 2015-02-05 04:37
But the default value (stock sensu) is to not have check keepalives?

**Comment by roobert** [comment] 2015-02-05 07:46
@solarkennedy ah sorry, to be clear: when I said "as-is", I meant from the current state of the patch, i.e: https://github.com/roobert/sensu/compare/a6db42dce674044b7b1ff8e0ea0304d95ec9054f%5E%5E...a6db42dce674044b7b1ff8e0ea0304d95ec9054#diff-b1352d95ed2d2b3454a9cbf22e47a38aR575

**Comment by solarkennedy** [comment] 2015-02-06 15:48
But the current state of the patch, won't it send check keepalives on every missing check? I don't see a "gate" on turning it on or off.

**Comment by roobert** [comment] 2015-02-06 16:19
@solarkennedy how about this: https://github.com/roobert/sensu/compare/3b0d4f0af625fefd490063dd41bc266cf60729c3%5E%5E...3b0d4f0af625fefd490063dd41bc266cf60729c3

**Comment by solarkennedy** [comment] 2015-02-06 16:30
Yea, I think we are getting closer. Can you make the output more helpful? How about "Check TTL of #{ttl} has expired. Last heard ${seconds} seconds ago." Also you have to set the output code to 2, otherwise no alert will go out. Also I think you need to "merge" the last check json so the right handlers and other metadata go out.

Now, the _real_ niceity here is merging the keepalive and ttl logic. Keepalives should be just another case of a TTL expiring if you ask me or @hashbrowncipher. For my fork I won't make you do that, but @portertech might. It would a nice-to-have if this feature didn't increase the complexity of sensu too much, and merged the behavior between keepalive checks and this kind of staleness, as they are the same idea. In this patch we are introducing a new word (ttl) and new concept, which is different then the keepalive.

But wouldn't it be cool if they were the same? (granted, now you have to come up with warn and crit thresholds)

**Comment by roobert** [comment] 2015-02-06 17:03
@solarkennedy I've added the client bits: https://github.com/roobert/sensu/commit/1252161eaba6fea33a9e9ffff7158394f91e8814

The problem is that the check data isn't stored in redis when the status is 0 so it's not always possible to deep merge the check.

I agree with what you're saying about the keepalive and ttl logic but I'm worried the changes I've made so far are already too big. It would be good to get @portertechs view on this before proceeding with much heavier changes.

**Comment by solarkennedy** [comment] 2015-02-06 18:09
Ah crap! :( I knew that 0 events were not kept as "events", but I forgot that they were not in redis at all.
.......

How is it going to know what handlers to use?

I'm running out of steam. I'm starting to think an extension is the best way to go about this.
Storing the metadata and everything on every "ok" event is expensive and doesn't scale, @portertech is right about that.

The checks (in my use-case) that require a staleness/ttl are small in number, so I think that can justify this, but it should certainly be an "opt-in" experience. 99% of checks don't need to store status 0 event data or need to chirp up if they go away.

**Comment by roobert** [comment] 2015-02-06 19:08
I've been playing about with this: https://github.com/roobert/sensu_handler_status_zero/blob/master/status_zero.rb

**Comment by roobert** [comment] 2015-02-06 20:34
Is the overhead of processing and storing all check data really that much? It's what we're used to with Nagios. Don't the benefits of having that extra data outweigh any performance hit?

**Comment by roobert** [comment] 2015-02-06 23:30
@solarkennedy - I had a good chat with Portertech on IRC and he explained to me something which I should have realised: event data is data signifying state-changes which is why it doesn't make much sense to store status-0 events. I think I missed this obvious detail as OK data is _always_ sent to the server (for various reasons), even though it isn't a state change.

Portertech pointed out it would make more sense to take specific pieces of the event data and persist it in Redis in the form of 'result' data. This would include handlers, etc. so would be the answer to being able to properly route check keepalives.

Once the major [refactor](https://github.com/sensu/sensu/pull/839/files) is complete then hopefully we can start raising some PRs to get these features merged in.

**Comment by solarkennedy** [comment] 2015-02-06 23:34
For yelp's use case, it must be the complete event json in order to be useful.

The only way I can see this is to have an extension store the event data on these checks that need it, so it can be retrieved if they do not check in.

**Comment by solarkennedy** [comment] 2015-02-06 23:51
@keymone I think you are just plain right. We should build this as an extension.

It doesn't have to be in core, especially if it requires architectural changes.

**Comment by roobert** [comment] 2015-03-29 15:37
I went ahead and implemented this on 0.17 - https://github.com/sensu/sensu/pull/910

This includes various changes I talked to @portertech about making, for example: storing 'result' data in redis for checks regardless of status. I think it'll do what you want and hopefully it'll make it into Sensu as it conforms to @portertechs wishes too.

**Comment by solarkennedy** [comment] 2016-04-10 18:35
Closing as this is implemented upstream as `ttl`.

**Closed as completed by solarkennedy** 2016-04-10 18:35 UTC
